name: Trial CI Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to checkout'
        required: true
        default: "v1.0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}

      # 步骤 2：设置 Java 环境
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      # 步骤 3：压缩代码（排除 .git 目录）
      - name: Compress code
        run: |
          tar -czvf source_code.tar.gz --exclude='.git' .

      # 步骤 4：上传压缩包作为构建产物
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: source_code.tar.gz
          path: source_code.tar.gz
