
name: Trial CI Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to checkout'
        required: true
        default: "v1.0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clean workspace
        run: |          
          rm -rf *

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: v1.1

      # 步骤 2：设置 Java 环境
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      # 步骤 3：使用 git archive 压缩代码
      - name: Compress code using git archive
        run: |          
          git archive --format=tar.gz --output=source_code.tar.gz HEAD

      # 步骤 4：上传压缩包作为构建产物
      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: documentation-pdfs
          path: source_code.tar.gz

